AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  IoTButtonYesNo:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::020315610929:role/service-role/IoTButton_YesNo-role-wrth2okn
      Environment:
        Variables:
          CLICK_TYPE_END: DOUBLE
          CLICK_TYPE_NO: LONG
          CLICK_TYPE_YES: SINGLE
          DYNAMO_TABLE_NAME: yesno_result
          IOT_TOPIC: yesno/result
      Tags:
        AppCategory: IoTButton_YesNo
